### ISSUE TITLE
[Feature request] Add the option to hide the console app window

### ISSUE THREAD

**Issue by skygate2012** [akiirui/mpv-handler#33]
It would be great to add the option to hide the console app window in the config.

**Comment by akiirui** [comment]
Sorry, there are no plans to add the option to hide the console window.

Because if the console window is hidden, users will not see any information about errors.

That's why I recommend windows users to choose the binary to `mpv.com` instead of `mpv.exe` (`exe` ver doesn't output any information).

**Comment by skygate2012** [comment]
Ah ok. Maybe add a log output option, and run the log file with notepad if any error occurs. Or just turn it into a GUI application XD
Anyway, in the meantime, for those of you who find the extra console window an abomination:

mpv-handler.vbs:
```
CreateObject("WScript.Shell").Run CreateObject("Scripting.FileSystemObject").GetParentFolderName(WScript.ScriptFullName) & "\mpv-handler.exe " & WScript.Arguments(0) & "", 0
```

```
reg add "HKCR\mpv\shell\open\command" /d "WScript \"%cd%\mpv-handler.vbs\" \"%1\"" /f
```

**Comment by akiirui** [comment]
> Maybe add a log output option, and run the log file with notepad if any error occurs.

Opening a console window also lets the user know that it has been run.

This is because the mpv window is not displayed while ytdl-hook is parsing.

In poor network conditions, parsing takes some time, and users who click the play button but don't get any feedback for a long time. They may press the button several times.

> Or just turn it into a GUI application

I want to keep it simple.

> Anyway, in the meantime, for those of you who find the extra console window an abomination:

Yep, if you hate the console window, try your way to hide it.

**Comment by akiirui** [comment]
New release have another method to hide console window.
For details, see Release page.
