### ISSUE TITLE
Member videos/streams

### ISSUE THREAD

**Issue by kkshl** [akiirui/mpv-handler#7]
Can you add a toggle for member content? There's a way of watching member streams/videos of the channel you are subscribed to via mpv but it's quite complicated in its own way, would be nice to have it in the userscript.

**Comment by akiirui** [comment]
Do you mean `--cookies` or `--username & --password`?

If it is `--cookies`.
Cannot support, because userscript cannot get HttpOnly cookies.
(So far, only `Tampermonkey Beta` provided the `GM_cookies` to read HttpOnly cookies.)

So, `--cookies` method to play member videos will not be supported until all userscript manager provided the `GM_cookies` API.

If it is `--username & --password`.
Save account password in cleartext, it's dangerous.

**Comment by akiirui** [comment]
But we have another way to use `--cookies` method.

1. Save cookies to file manually.
2. Add a option **Try pass cookies** in userscript.
3. When enable this option, mpv-handler will try pass the cookies file to youtube-dl.

Is this method acceptable?

**Comment by kkshl** [comment]
I have got the cookies.txt, can you help me show where I can add it to the script?

**Comment by akiirui** [comment]
> I have got the cookies.txt, can you help me show where I can add it to the script?

I will add this feature to userscript and mpv-handlers in a few days.

**Comment by akiirui** [comment]
Already supported pass cookies to youtube-dl.

See [README#pass-cookies-to-youtube-dl](https://github.com/akiirui/userscript/blob/main/play-with-mpv-handler/README.md#pass-cookies-to-youtube-dl)
